export const lectures = [
  // 인문학 (10개)
  {
    id: 1,
    title: "서양 문학의 이해와 감상",
    instructor: "김인문",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "인문학",
    keyword: '',
    likes: 128,
    students: 256,
    group: '온라인',
    href: "/lectures/1"
  },
  {
    id: 2,
    title: "동양 고전 읽기의 즐거움",
    instructor: "이고전",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "인문학",
    keyword: '',
    likes: 156,
    students: 189,
    group: '오프라인',
    href: "/lectures/2"
  },
  {
    id: 3,
    title: "세계 신화와 문화 이야기",
    instructor: "박문화",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "인문학",
    keyword: '',
    likes: 245,
    students: 312,
    group: '온라인',
    href: "/lectures/3"
  },
  {
    id: 4,
    title: "현대 문예의 흐름과 해석",
    instructor: "최예술",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "인문학",
    keyword: '',
    likes: 167,
    students: 289,
    group: '온라인',
    href: "/lectures/4"
  },
  {
    id: 5,
    title: "한국 문학사의 이해",
    instructor: "정문학",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "인문학",
    keyword: '',
    likes: 198,
    students: 234,
    group: '오프라인',
    href: "/lectures/5"
  },
  {
    id: 6,
    title: "비교문학으로 보는 세계",
    instructor: "김비교",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "인문학",
    keyword: '',
    likes: 178,
    students: 245,
    group: '온라인',
    href: "/lectures/6"
  },
  {
    id: 7,
    title: "문화인류학 입문",
    instructor: "이인류",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "인문학",
    keyword: '',
    likes: 223,
    students: 278,
    group: '오프라인',
    href: "/lectures/7"
  },
  {
    id: 8,
    title: "언어학의 기초",
    instructor: "박언어",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "인문학",
    keyword: '',
    likes: 145,
    students: 198,
    group: '온라인',
    href: "/lectures/8"
  },
  {
    id: 9,
    title: "예술사의 흐름",
    instructor: "최예술",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "인문학",
    keyword: '',
    likes: 167,
    students: 223,
    group: '온라인',
    href: "/lectures/9"
  },
  {
    id: 10,
    title: "고전 강독과 해석",
    instructor: "정고전",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "인문학",
    keyword: '',
    likes: 189,
    students: 245,
    group: '오프라인',
    href: "/lectures/10"
  },

  // 철학 (10개)
  {
    id: 11,
    title: "서양철학의 역사",
    instructor: "김철학",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "철학",
    keyword: '',
    likes: 234,
    students: 312,
    group: '온라인',
    href: "/lectures/11"
  },
  {
    id: 12,
    title: "동양철학 입문",
    instructor: "이동양",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "철학",
    keyword: '',
    likes: 156,
    students: 234,
    group: '온라인',
    href: "/lectures/12"
  },
  {
    id: 13,
    title: "현대철학의 이해",
    instructor: "박현대",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "철학",
    keyword: '',
    likes: 178,
    students: 245,
    group: '오프라인',
    href: "/lectures/13"
  },
  {
    id: 14,
    title: "윤리학의 기초",
    instructor: "최윤리",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "철학",
    keyword: '',
    likes: 203,
    students: 289,
    group: '온라인',
    href: "/lectures/14"
  },
  {
    id: 15,
    title: "논리학 입문",
    instructor: "정논리",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "철학",
    keyword: '',
    likes: 167,
    students: 223,
    group: '온라인',
    href: "/lectures/15"
  },
  {
    id: 16,
    title: "실존주의 철학",
    instructor: "김실존",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "철학",
    keyword: '',
    likes: 189,
    students: 256,
    group: '오프라인',
    href: "/lectures/16"
  },
  {
    id: 17,
    title: "형이상학의 세계",
    instructor: "이형이",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "철학",
    keyword: '',
    likes: 145,
    students: 198,
    group: '온라인',
    href: "/lectures/17"
  },
  {
    id: 18,
    title: "철학적 사고법",
    instructor: "박사고",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "철학",
    keyword: '',
    likes: 223,
    students: 289,
    group: '온라인',
    href: "/lectures/18"
  },
  {
    id: 19,
    title: "도덕철학의 이해",
    instructor: "최도덕",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "철학",
    keyword: '',
    likes: 156,
    students: 212,
    group: '오프라인',
    href: "/lectures/19"
  },
  {
    id: 20,
    title: "정치철학 입문",
    instructor: "정정치",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "철학",
    keyword: '',
    likes: 178,
    students: 234,
    group: '온라인',
    href: "/lectures/20"
  },

  // 심리학 (8개)
  {
    id: 21,
    title: "심리학의 기초",
    instructor: "김심리",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "심리학",
    keyword: '',
    likes: 289,
    students: 345,
    group: '온라인',
    href: "/lectures/21"
  },
  {
    id: 22,
    title: "발달심리학",
    instructor: "이발달",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "심리학",
    keyword: '',
    likes: 198,
    students: 267,
    group: '오프라인',
    href: "/lectures/22"
  },
  {
    id: 23,
    title: "성격심리학",
    instructor: "박성격",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "심리학",
    keyword: '',
    likes: 167,
    students: 223,
    group: '온라인',
    href: "/lectures/23"
  },
  {
    id: 24,
    title: "임상심리학 입문",
    instructor: "최임상",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "심리학",
    keyword: '',
    likes: 234,
    students: 289,
    group: '온라인',
    href: "/lectures/24"
  },
  {
    id: 25,
    title: "상담심리학의 이해",
    instructor: "정상담",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "심리학",
    keyword: '',
    likes: 178,
    students: 245,
    group: '오프라인',
    href: "/lectures/25"
  },
  {
    id: 26,
    title: "인지심리학",
    instructor: "김인지",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "심리학",
    keyword: '',
    likes: 156,
    students: 212,
    group: '온라인',
    href: "/lectures/26"
  },
  {
    id: 27,
    title: "사회심리학",
    instructor: "이사회",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "심리학",
    keyword: '',
    likes: 203,
    students: 278,
    group: '오프라인',
    href: "/lectures/27"
  },
  {
    id: 28,
    title: "학습심리학",
    instructor: "박학습",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "심리학",
    keyword: '',
    likes: 189,
    students: 256,
    group: '온라인',
    href: "/lectures/28"
  },

  // 경제학 (8개)
  {
    id: 29,
    title: "경제학 원론",
    instructor: "김경제",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "경제학",
    keyword: '',
    likes: 245,
    students: 312,
    group: '오프라인',
    href: "/lectures/29"
  },
  {
    id: 30,
    title: "미시경제학",
    instructor: "이미시",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "경제학",
    keyword: '',
    likes: 178,
    students: 234,
    group: '온라인',
    href: "/lectures/30"
  },
  {
    id: 31,
    title: "거시경제학",
    instructor: "박거시",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "경제학",
    keyword: '',
    likes: 203,
    students: 278,
    group: '오프라인',
    href: "/lectures/31"
  },
  {
    id: 32,
    title: "금융경제학",
    instructor: "최금융",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "경제학",
    keyword: '',
    likes: 167,
    students: 223,
    group: '온라인',
    href: "/lectures/32"
  },
  {
    id: 33,
    title: "국제경제학",
    instructor: "정국제",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "경제학",
    keyword: '',
    likes: 189,
    students: 245,
    group: '오프라인',
    href: "/lectures/33"
  },
  {
    id: 34,
    title: "행동경제학",
    instructor: "김행동",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "경제학",
    keyword: '',
    likes: 156,
    students: 212,
    group: '온라인',
    href: "/lectures/34"
  },
  {
    id: 35,
    title: "개발경제학",
    instructor: "이개발",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "경제학",
    keyword: '',
    likes: 223,
    students: 289,
    group: '오프라인',
    href: "/lectures/35"
  },
  {
    id: 36,
    title: "환경경제학",
    instructor: "박환경",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "경제학",
    keyword: '',
    likes: 178,
    students: 234,
    group: '온라인',
    href: "/lectures/36"
  },

  // 자기계발 (7개)
  {
    id: 37,
    title: "시간 관리의 기술",
    instructor: "김시간",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "자기계발",
    keyword: '',
    likes: 289,
    students: 356,
    group: '오프라인',
    href: "/lectures/37"
  },
  {
    id: 38,
    title: "목표 설정과 실천",
    instructor: "이목표",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "자기계발",
    keyword: '',
    likes: 234,
    students: 312,
    group: '온라인',
    href: "/lectures/38"
  },
  {
    id: 39,
    title: "습관 형성의 심리학",
    instructor: "박습관",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "자기계발",
    keyword: '',
    likes: 198,
    students: 267,
    group: '온라인',
    href: "/lectures/39"
  },
  {
    id: 40,
    title: "효과적인 의사소통",
    instructor: "최소통",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "자기계발",
    keyword: '',
    likes: 167,
    students: 223,
    group: '오프라인',
    href: "/lectures/40"
  },
  {
    id: 41,
    title: "창의적 문제해결",
    instructor: "정창의",
    thumbnailUrl: "/placeholder.jpg",
    depth: "고급",
    category: "자기계발",
    keyword: '',
    likes: 223,
    students: 289,
    group: '온라인',
    href: "/lectures/41"
  },
  {
    id: 42,
    title: "감정 관리와 스트레스 해소",
    instructor: "김감정",
    thumbnailUrl: "/placeholder.jpg",
    depth: "중급",
    category: "자기계발",
    keyword: '',
    likes: 178,
    students: 245,
    group: '오프라인',
    href: "/lectures/42"
  },
  {
    id: 43,
    title: "자기주도적 학습법",
    instructor: "이학습",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "자기계발",
    keyword: '',
    likes: 156,
    students: 212,
    group: '온라인',
    href: "/lectures/43"
  },

  // 리더십 (7개)
  {
    id: 44,
    title: "리더십의 기초",
    instructor: "박리더",
    thumbnailUrl: "/placeholder.jpg",
    depth: "초급",
    category: "리더십",
    keyword: '',
    likes: 245,
    students: 323,
    group: '온라인',
    href: "/lectures/44"
  },
]